apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wildfly-operator
  template:
    metadata:
      labels:
        name: wildfly-operator
    spec:
      serviceAccountName: wildfly-operator
      containers:
        - name: wildfly-operator
          image: quay.io/wildfly/wildfly-operator:latest
          command:
          - wildfly-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "wildfly-operator"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: wildfly-operator

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wildfly-operator
subjects:
  - kind: ServiceAccount
    name: wildfly-operator
roleRef:
  kind: Role
  name: wildfly-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wildfly-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - pods/log
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - services/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - deployments/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - wildfly.org
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
